### ISSUE TITLE
List Recommendations

### ISSUE THREAD

**Issue by clover00000** [CSCI-GA-2820-SU24-001/recommendations#10]
**As a** Developer
**I need** the ability to list any recommendation  
**So that** I can see the overview of recommended product combinations
   
 ### Details and Assumptions
 * The recommendations will be stored in a PostgreSQL database.
 * Each recommendation includes a unique id, collection of items, and frequency
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given there are multiple recommendations in the database
 When I request to list recommendations according to their unique id, items included, or frequency
 Then there should be a view of listed recommendations
```

**Comment by Dreamsofriver** [comment]
![image](https://github.com/CSCI-GA-2820-SU24-001/recommendations/assets/77102865/8da08583-9b90-4350-9191-c6ae0ebcf21b)
